version: '3.8'
volumes:
  postgis:
  caddy_data:
  caddy_config:

services:
  db:
    image: postgis/postgis
    container_name: postgis
    build: 
      context: ./postgis
      dockerfile: Dockerfile
    volumes:
      - postgis:/var/lib/postgresql/data
      - ./backups:/opt/backups
    # networks:
      # - cstreet
    ports:
      - '5432:5432'
    env_file: ./postgis/.env
    restart: on-failure
  # gunicorn:
  #   container_name: gunicorn
  #   build:
  #     context: .
  #     dockerfile: gunicorn.dockerfile
  #   environment:
  #     - APP_MODULE=conf.wsgi
  #     - GDAL_LIBRARY_PATH=/install/gdal-3.2.1
  #   volumes:
  #     - ./app:/app
  #   tmpfs:
  #     - /tmp
    # networks:
    #   - cstreet
  server:
    image: caddy
    container_name: caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - $STATIC_PATH:/srv/app/static
      - $MEDIA_PATH:/srv/app/media
      - ./Dropbox:/srv/app/static/Dropbox
    # networks:
      # - cstreet
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    # networks:
      # - cstreet
    ports:
      - "5051:80"
    env_file: ./postgis/.env
    restart: on-failure
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    # networks:
      # - cstreet
    ports:
      - "5672:5672"
    env_file: ./rabbitmq/.env
    restart: always
  shynet:
    image: milesmcc/shynet
    container_name: shynet
    # networks:
      # - cstreet
    env_file: ./shynet/.env
    restart: always
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    # networks:
      # - cstreet
    env_file: ./redis/.env
    restart: always
  # imgproxy:
  #   image: darthsim/imgproxy
  #   container_name: imgproxy
    # networks:
    #   - cstreet
  #   ports:
  #     - "8080:8080"
  #   env_file: ./imgproxy/.env
  # dropbox:
  #   image: otherguy/dropbox
  #   container_name: dropbox
  #   environment:
  #     - DROPBOX_UID
  #     - DROPBOX_GID
  #   volumes:
  #     - ./Dropbox:/opt/dropbox/Dropbox
  #     - ./.dropbox:/opt/dropbox/.dropbox
  #     - /etc/timezone:/etc/timezone
  #     - /etc/localtime:/etc/localtime
    # networks:
    #   - cstreet
  #   restart: always
  # splash:
  #   image: scrapinghub/splash
  #   container_name: splash
    # networks:
    #   - cstreet
  #   ports:
  #     - "8050:8050"

# networks:
#   cstreet:
#     driver: bridge
