version: '3.8'
volumes:
  postgres:
  caddy_data:
  caddy_config:

services:
  # db:
  #   build: 
  #     context: ./postgres-postgis
  #     dockerfile: Dockerfile
  #   image: postgis/postgis
  #   container_name: postgres-postgis
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #     - ./backups:/opt/backups
  #   networks:
  #     - postgres_conn
  #   ports:
  #     - '5432:5432'
  #   env_file: ./postgres-postgis/.env
  #   restart: on-failure
  server:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - $STATIC_PATH:/srv/app/static
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   depends_on:
  #     - db
  #   ports:
  #     - "5051:80"
  #   env_file: ./postgres-postgis/.env
  #   restart: on-failure
  # imgproxy:
  #   image: darthsim/imgproxy
  #   container_name: imgproxy
  #   ports:
  #     - "8080:8080"
  #   env_file: ./imgproxy/.env
  # splash:
  #   image: scrapinghub/splash
  #   container_name: splash
  #   ports:
  #     - "8050:8050"

# networks:
#   postgres_conn:
#     driver: bridge
